name: Build with Gradle

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Assemble the project
        run: ./gradlew build

      - name: Upload Fabric artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-fabric
          path: fabric/build/libs/*.jar
          retention-days: 90
